version: '3.8'

services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
    ports:
      - 27018:27017
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data
    ports:
      - 5433:5432
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306